// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainerLibrary.Models;

#nullable disable

namespace TrainerLibrary.Migrations
{
    [DbContext(typeof(ZelisTrainerEFDBContext))]
    partial class ZelisTrainerEFDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainerLibrary.Models.Trainer", b =>
                {
                    b.Property<string>("TrainerId")
                        .HasColumnType("char(6)");

                    b.Property<string>("TrainerEmail")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TrainerPhoneNo")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("TrainerType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("TrainerId");

                    b.ToTable("Trainer");
                });
#pragma warning restore 612, 618
        }
    }
}
