// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnologyLibrary.Models;

#nullable disable

namespace TechnologyLibrary.Migrations
{
    [DbContext(typeof(ZelisTechnologyEFDBContext))]
    [Migration("20251028051933_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnologyLibrary.Models.Technology", b =>
                {
                    b.Property<string>("TechnologyId")
                        .HasColumnType("char(6)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("TechnologyName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("TechnologyId");

                    b.ToTable("Technology");
                });
#pragma warning restore 612, 618
        }
    }
}
