// <auto-generated />
using EmployeeLibrary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeLibrary.Migrations
{
    [DbContext(typeof(ZelisEmployeeEFDBContext))]
    [Migration("20251028051858_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeLibrary.Models.Employee", b =>
                {
                    b.Property<string>("EmpId")
                        .HasColumnType("char(6)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("EmpEmail")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("EmpPhoneNo")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.HasKey("EmpId");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
